# Generated by Django 4.2.7 on 2025-10-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('product_type', models.CharField(choices=[('chatbot', 'Chatbot'), ('web_simple', 'Web Simple'), ('suit_commerce', 'Suit Commerce'), ('automation', 'Automatización RPA'), ('data_migration', 'Migración de Datos'), ('custom_development', 'Desarrollo a Medida')], max_length=50, verbose_name='Tipo de Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('maintenance', 'En Mantenimiento'), ('discontinued', 'Discontinuado')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='subscription_type',
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado'), ('development', 'En Desarrollo')], default='active', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Mensual')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Servicio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
            options={
                'verbose_name': 'Producto del Cliente',
                'verbose_name_plural': 'Productos del Cliente',
                'unique_together': {('client', 'product')},
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='products',
            field=models.ManyToManyField(through='accounts.ClientProduct', to='accounts.product', verbose_name='Productos/Servicios'),
        ),
    ]
